### ISSUE TITLE
Add developers and mentors to website

### ISSUE THREAD

**Issue by mariobehling** [fossasia/pslab.fossasia.org#63]
* Devs
* Mentors: Praveen Patil (Gnovi), Kiwi, Darwin Gosal, Shams Jaber, Ansgar Schmidt, Haggen So, Victoria Bondarchuk, Wan Leung Wong, Mitch Altman, Greg Austic, Soong Chee Gi, Lorenz Gerber

**Comment by rishabh-bansal** [comment]
@mariobehling Can I work on this? Actually I am already working on this, but it would be better if you assign this to me :) @mariobehling  @wavicles  @CloudyPadmal

**Comment by anshulwadhawan** [comment]
From where can I get the data about these devs and mentors ?
@mariobehling

**Comment by lapmid** [comment]
@mariobehling  kindly see #72 i have also fixed #21 in this and added some mentors

**Comment by Remorax** [comment]
Is anybody still working on this issue? I would like to take this up :)
@mariobehling @CloudyPadmal @wavicles

**Comment by Remorax** [comment]
Also, please provide links to the data for all the developers and mentors @mariobehling @CloudyPadmal @wavicles

**Comment by jigyasa-grover** [comment]
@Remorax Seems like this issue is still unresolved, you could go ahead with it. Thanks !

**Comment by Remorax** [comment]
@jigyasa-grover Sure I'll do it, but where do I find the photos, the info etc for the same?

**Comment by abishekvashok** [comment]
Use the fossasia sites, or try to contact mentors and dev haing slack or gitter. @Remorax

**Comment by Remorax** [comment]
Sure, I'll make a PR within a couple of days :)

**Comment by abishekvashok** [comment]
@Remorax sure
